// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// C_context_cleaner
NumericVector C_context_cleaner(const NumericMatrix& x, int ncols, int nrows, int band, int window_size, int target_class, int mode_class);
RcppExport SEXP _restoreutils_C_context_cleaner(SEXP xSEXP, SEXP ncolsSEXP, SEXP nrowsSEXP, SEXP bandSEXP, SEXP window_sizeSEXP, SEXP target_classSEXP, SEXP mode_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type target_class(target_classSEXP);
    Rcpp::traits::input_parameter< int >::type mode_class(mode_classSEXP);
    rcpp_result_gen = Rcpp::wrap(C_context_cleaner(x, ncols, nrows, band, window_size, target_class, mode_class));
    return rcpp_result_gen;
END_RCPP
}
// C_na_cleaner
NumericVector C_na_cleaner(const NumericMatrix& x, int ncols, int nrows, int band, int window_size);
RcppExport SEXP _restoreutils_C_na_cleaner(SEXP xSEXP, SEXP ncolsSEXP, SEXP nrowsSEXP, SEXP bandSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(C_na_cleaner(x, ncols, nrows, band, window_size));
    return rcpp_result_gen;
END_RCPP
}
// C_remap_values
NumericMatrix C_remap_values(NumericMatrix& data, int source, int target);
RcppExport SEXP _restoreutils_C_remap_values(SEXP dataSEXP, SEXP sourceSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type source(sourceSEXP);
    Rcpp::traits::input_parameter< int >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(C_remap_values(data, source, target));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_transition_analysis
NumericMatrix C_trajectory_transition_analysis(NumericMatrix data, int reference_class, int neighbor_class);
RcppExport SEXP _restoreutils_C_trajectory_transition_analysis(SEXP dataSEXP, SEXP reference_classSEXP, SEXP neighbor_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type reference_class(reference_classSEXP);
    Rcpp::traits::input_parameter< int >::type neighbor_class(neighbor_classSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_transition_analysis(data, reference_class, neighbor_class));
    return rcpp_result_gen;
END_RCPP
}
// C_urban_transition
NumericVector C_urban_transition(NumericMatrix data, int urban_id, int nb_id);
RcppExport SEXP _restoreutils_C_urban_transition(SEXP dataSEXP, SEXP urban_idSEXP, SEXP nb_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type urban_id(urban_idSEXP);
    Rcpp::traits::input_parameter< int >::type nb_id(nb_idSEXP);
    rcpp_result_gen = Rcpp::wrap(C_urban_transition(data, urban_id, nb_id));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_neighbor_analysis
NumericMatrix C_trajectory_neighbor_analysis(NumericMatrix data, int reference_class, int replacement_class);
RcppExport SEXP _restoreutils_C_trajectory_neighbor_analysis(SEXP dataSEXP, SEXP reference_classSEXP, SEXP replacement_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type reference_class(reference_classSEXP);
    Rcpp::traits::input_parameter< int >::type replacement_class(replacement_classSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_neighbor_analysis(data, reference_class, replacement_class));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_neighbor_consistency_analysis
NumericMatrix C_trajectory_neighbor_consistency_analysis(NumericMatrix data, int reference_class);
RcppExport SEXP _restoreutils_C_trajectory_neighbor_consistency_analysis(SEXP dataSEXP, SEXP reference_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type reference_class(reference_classSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_neighbor_consistency_analysis(data, reference_class));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_neighbor_consistency_analysis_with_mask
NumericMatrix C_trajectory_neighbor_consistency_analysis_with_mask(NumericMatrix data, NumericMatrix mask, int data_class, int mask_class);
RcppExport SEXP _restoreutils_C_trajectory_neighbor_consistency_analysis_with_mask(SEXP dataSEXP, SEXP maskSEXP, SEXP data_classSEXP, SEXP mask_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type data_class(data_classSEXP);
    Rcpp::traits::input_parameter< int >::type mask_class(mask_classSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_neighbor_consistency_analysis_with_mask(data, mask, data_class, mask_class));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_neighbor_majority_analysis
NumericMatrix C_trajectory_neighbor_majority_analysis(NumericMatrix data, int reference_class, DataFrame target_class_map);
RcppExport SEXP _restoreutils_C_trajectory_neighbor_majority_analysis(SEXP dataSEXP, SEXP reference_classSEXP, SEXP target_class_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type reference_class(reference_classSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type target_class_map(target_class_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_neighbor_majority_analysis(data, reference_class, target_class_map));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_neighbor_majority_analysis_target
NumericMatrix C_trajectory_neighbor_majority_analysis_target(NumericMatrix data, int reference_class, Rcpp::Nullable<Rcpp::IntegerVector> target_class, Rcpp::Nullable<Rcpp::DataFrame> target_class_map);
RcppExport SEXP _restoreutils_C_trajectory_neighbor_majority_analysis_target(SEXP dataSEXP, SEXP reference_classSEXP, SEXP target_classSEXP, SEXP target_class_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type reference_class(reference_classSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type target_class(target_classSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::DataFrame> >::type target_class_map(target_class_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_neighbor_majority_analysis_target(data, reference_class, target_class, target_class_map));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_deforestation_consistency
NumericMatrix C_trajectory_deforestation_consistency(NumericMatrix data, int reference_class, Rcpp::Nullable<Rcpp::IntegerVector> target_class, Rcpp::Nullable<Rcpp::DataFrame> target_class_map);
RcppExport SEXP _restoreutils_C_trajectory_deforestation_consistency(SEXP dataSEXP, SEXP reference_classSEXP, SEXP target_classSEXP, SEXP target_class_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type reference_class(reference_classSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type target_class(target_classSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::DataFrame> >::type target_class_map(target_class_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_deforestation_consistency(data, reference_class, target_class, target_class_map));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_water_analysis
NumericMatrix C_trajectory_water_analysis(NumericMatrix data, int water_class, DataFrame target_class_map, IntegerVector excluded_values);
RcppExport SEXP _restoreutils_C_trajectory_water_analysis(SEXP dataSEXP, SEXP water_classSEXP, SEXP target_class_mapSEXP, SEXP excluded_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type water_class(water_classSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type target_class_map(target_class_mapSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type excluded_values(excluded_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_water_analysis(data, water_class, target_class_map, excluded_values));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_urban_analysis
NumericMatrix C_trajectory_urban_analysis(NumericMatrix data, NumericMatrix mask, int urban_class_id, int forest_class_id, int forest_class_id_mask);
RcppExport SEXP _restoreutils_C_trajectory_urban_analysis(SEXP dataSEXP, SEXP maskSEXP, SEXP urban_class_idSEXP, SEXP forest_class_idSEXP, SEXP forest_class_id_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type urban_class_id(urban_class_idSEXP);
    Rcpp::traits::input_parameter< int >::type forest_class_id(forest_class_idSEXP);
    Rcpp::traits::input_parameter< int >::type forest_class_id_mask(forest_class_id_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_urban_analysis(data, mask, urban_class_id, forest_class_id, forest_class_id_mask));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_vs_analysis
NumericMatrix C_trajectory_vs_analysis(NumericMatrix data, int vs_class, IntegerVector pasture_class, int target_class);
RcppExport SEXP _restoreutils_C_trajectory_vs_analysis(SEXP dataSEXP, SEXP vs_classSEXP, SEXP pasture_classSEXP, SEXP target_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type vs_class(vs_classSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pasture_class(pasture_classSEXP);
    Rcpp::traits::input_parameter< int >::type target_class(target_classSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_vs_analysis(data, vs_class, pasture_class, target_class));
    return rcpp_result_gen;
END_RCPP
}
// C_validation_compare_versions
NumericMatrix C_validation_compare_versions(NumericMatrix data, NumericMatrix mask, int data_class, int mask_class);
RcppExport SEXP _restoreutils_C_validation_compare_versions(SEXP dataSEXP, SEXP maskSEXP, SEXP data_classSEXP, SEXP mask_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type data_class(data_classSEXP);
    Rcpp::traits::input_parameter< int >::type mask_class(mask_classSEXP);
    rcpp_result_gen = Rcpp::wrap(C_validation_compare_versions(data, mask, data_class, mask_class));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_restoreutils_C_context_cleaner", (DL_FUNC) &_restoreutils_C_context_cleaner, 7},
    {"_restoreutils_C_na_cleaner", (DL_FUNC) &_restoreutils_C_na_cleaner, 5},
    {"_restoreutils_C_remap_values", (DL_FUNC) &_restoreutils_C_remap_values, 3},
    {"_restoreutils_C_trajectory_transition_analysis", (DL_FUNC) &_restoreutils_C_trajectory_transition_analysis, 3},
    {"_restoreutils_C_urban_transition", (DL_FUNC) &_restoreutils_C_urban_transition, 3},
    {"_restoreutils_C_trajectory_neighbor_analysis", (DL_FUNC) &_restoreutils_C_trajectory_neighbor_analysis, 3},
    {"_restoreutils_C_trajectory_neighbor_consistency_analysis", (DL_FUNC) &_restoreutils_C_trajectory_neighbor_consistency_analysis, 2},
    {"_restoreutils_C_trajectory_neighbor_consistency_analysis_with_mask", (DL_FUNC) &_restoreutils_C_trajectory_neighbor_consistency_analysis_with_mask, 4},
    {"_restoreutils_C_trajectory_neighbor_majority_analysis", (DL_FUNC) &_restoreutils_C_trajectory_neighbor_majority_analysis, 3},
    {"_restoreutils_C_trajectory_neighbor_majority_analysis_target", (DL_FUNC) &_restoreutils_C_trajectory_neighbor_majority_analysis_target, 4},
    {"_restoreutils_C_trajectory_deforestation_consistency", (DL_FUNC) &_restoreutils_C_trajectory_deforestation_consistency, 4},
    {"_restoreutils_C_trajectory_water_analysis", (DL_FUNC) &_restoreutils_C_trajectory_water_analysis, 4},
    {"_restoreutils_C_trajectory_urban_analysis", (DL_FUNC) &_restoreutils_C_trajectory_urban_analysis, 5},
    {"_restoreutils_C_trajectory_vs_analysis", (DL_FUNC) &_restoreutils_C_trajectory_vs_analysis, 4},
    {"_restoreutils_C_validation_compare_versions", (DL_FUNC) &_restoreutils_C_validation_compare_versions, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_restoreutils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
