# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_context_cleaner <- function(x, ncols, nrows, band, window_size, target_class, mode_class) {
    .Call(`_restoreutils_C_context_cleaner`, x, ncols, nrows, band, window_size, target_class, mode_class)
}

C_na_cleaner <- function(x, ncols, nrows, band, window_size) {
    .Call(`_restoreutils_C_na_cleaner`, x, ncols, nrows, band, window_size)
}

C_remap_values <- function(data, source, target) {
    .Call(`_restoreutils_C_remap_values`, data, source, target)
}

C_trajectory_transition_analysis <- function(data, reference_class, neighbor_class) {
    .Call(`_restoreutils_C_trajectory_transition_analysis`, data, reference_class, neighbor_class)
}

C_urban_transition <- function(data, urban_id, nb_id) {
    .Call(`_restoreutils_C_urban_transition`, data, urban_id, nb_id)
}

C_trajectory_neighbor_analysis <- function(data, reference_class, replacement_class) {
    .Call(`_restoreutils_C_trajectory_neighbor_analysis`, data, reference_class, replacement_class)
}

C_trajectory_neighbor_consistency_analysis <- function(data, reference_class) {
    .Call(`_restoreutils_C_trajectory_neighbor_consistency_analysis`, data, reference_class)
}

C_trajectory_neighbor_consistency_analysis_with_mask <- function(data, mask, data_class, mask_class) {
    .Call(`_restoreutils_C_trajectory_neighbor_consistency_analysis_with_mask`, data, mask, data_class, mask_class)
}

C_trajectory_neighbor_majority_analysis <- function(data, reference_class, target_class_map) {
    .Call(`_restoreutils_C_trajectory_neighbor_majority_analysis`, data, reference_class, target_class_map)
}

C_trajectory_neighbor_majority_analysis_target <- function(data, reference_class, target_class = NULL, target_class_map = NULL) {
    .Call(`_restoreutils_C_trajectory_neighbor_majority_analysis_target`, data, reference_class, target_class, target_class_map)
}

C_trajectory_past_reference <- function(data, reference_class, target_class = NULL, target_class_map = NULL) {
    .Call(`_restoreutils_C_trajectory_past_reference`, data, reference_class, target_class, target_class_map)
}

C_trajectory_water_analysis <- function(data, water_class, target_class_map, excluded_values) {
    .Call(`_restoreutils_C_trajectory_water_analysis`, data, water_class, target_class_map, excluded_values)
}

C_trajectory_urban_analysis <- function(data, mask, urban_class_id, forest_class_id, forest_class_id_mask) {
    .Call(`_restoreutils_C_trajectory_urban_analysis`, data, mask, urban_class_id, forest_class_id, forest_class_id_mask)
}

C_trajectory_vs_analysis <- function(data, vs_class, pasture_class, target_class) {
    .Call(`_restoreutils_C_trajectory_vs_analysis`, data, vs_class, pasture_class, target_class)
}

C_validation_compare_versions <- function(data, mask, data_class, mask_class) {
    .Call(`_restoreutils_C_validation_compare_versions`, data, mask, data_class, mask_class)
}

